
-- Poblamos la tabla rol
INSERT INTO rol (nombre) VALUES ('ADMIN');
INSERT INTO rol (nombre) VALUES ('OPERARIO');
INSERT INTO rol (nombre) VALUES ('USUARIO');

-- Poblamos la tabla genero
INSERT INTO genero (nombre) VALUES ('Masculino');
INSERT INTO genero (nombre) VALUES ('Femenino');
INSERT INTO genero (nombre) VALUES ('Otro');

INSERT INTO categoria_beneficio (nombre) VALUES ('Productos');
INSERT INTO categoria_beneficio (nombre) VALUES ('Estacionamiento');
INSERT INTO categoria_beneficio (nombre) VALUES ('Descuentos');
INSERT INTO categoria_beneficio (nombre) VALUES ('Entretenimiento');
INSERT INTO categoria_beneficio (nombre) VALUES ('Comidas');

-- Poblamos la tabla ecopunto
INSERT INTO ecopunto (nombre, descripcion) VALUES ('Ecopunto Rivadavia', 'Ecopunto situado en la sede academica rivadavia');
INSERT INTO ecopunto (nombre, descripcion) VALUES ('Ecopunto Libertad', 'Ecopunto situado en la calle libertad');

-- Poblamos la tabla beneficio
INSERT INTO beneficio (nombre, descripcion, costo, creado, imagen, categoria_id) VALUES ('Bolsa Ecologica', 'Obten tu bolsa hecha con materiales 100% reciclados', 50.25, '2023-11-16', 'https://www.elsiglodetorreon.com.mx/m/i/2020/04/1297120.jpeg', 1);
INSERT INTO beneficio (nombre, descripcion, costo, creado, imagen, categoria_id) VALUES ('Estacionamiento Medido Gratuito Por 8hs', 'Aprovecha este asombroso descuento y llévate los mejores chocolates de San Antonio de Areco.', 50.25, '2023-11-16', 'https://quedigital.com.ar/web/wp-content/uploads/2021/12/ESTACIONAMIENTO-MEDIDO-MAR-DEL-PLATA-1603-1200x900.jpg', 2);
INSERT INTO beneficio (nombre, descripcion, costo, creado, imagen, categoria_id) VALUES ('50% de Descuento en "La Olla de Cobre"', 'Aprovecha este asombroso descuento y llévate los mejores chocolates de San Antonio de Areco.', 50.25, '2023-11-16', 'http://www.alfajor-argentino.com.ar/images/slide-1608669268.jpg', 3);
INSERT INTO beneficio (nombre, descripcion, costo, creado, imagen, categoria_id) VALUES ('50% de Descuento en "La Olla de Cobre"', 'Aprovecha este asombroso descuento y llévate los mejores chocolates de San Antonio de Areco.', 50.25, '2023-11-16', 'http://www.alfajor-argentino.com.ar/images/slide-1608669268.jpg', 4);
INSERT INTO beneficio (nombre, descripcion, costo, creado, imagen, categoria_id) VALUES ('30% de Descuento en "El Fogón Matero"', 'Aprovecha este asombroso descuento y llévate los mejores mates de San Antonio de Areco.', 70.99, '2023-11-16', 'https://www.sanantoniodeareco.com/wp-content/uploads/2021/10/el-fogon-matero.jpg', 5);


-- Creamos un usuario
INSERT INTO usuario (nombre, apellido, email, clave, genero_id, balance) VALUES ('Gino', 'Canestrari', 'canestrari@duck.com', '$2y$10$8EGu/gTv.tmnVD1n.vmFouw556CZcKD9xXHiRE9SJcrkpSNUtAVT6', '1', '100.00');
INSERT INTO usuario (nombre, apellido, email, clave, genero_id, balance) VALUES ('John', 'Doe', 'jdoe@gmail.com', '$2y$10$8EGu/gTv.tmnVD1n.vmFouw556CZcKD9xXHiRE9SJcrkpSNUtAVT6', '1', '420');

-- Le asignamos al usuario creado el rol de administrador
INSERT INTO rol_de_usuario (usuario_id, rol_id) VALUES ('1', '1');
INSERT INTO rol_de_usuario (usuario_id, rol_id) VALUES ('2', '3');

-- Poblamos al usuario con reciclable
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet', 12.36, '2023-06-03', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('quam pede lobortis ligula sit amet eleifend pede libero quis', 0.15, '2023-12-22', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('at dolor quis odio consequat varius integer ac leo pellentesque', 13.33, '2023-05-19', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('quisque ut erat curabitur gravida nisi at nibh in hac', 3.2, '2023-02-17', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('ut dolor morbi vel lectus in quam fringilla rhoncus mauris', 2.84, '2023-01-28', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget', 5.65, '2023-11-16', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('volutpat sapien arcu sed augue aliquam erat volutpat in congue', 12.24, '2023-10-04', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('posuere cubilia curae nulla dapibus dolor vel est donec odio', 9.29, '2023-07-04', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('elementum in hac habitasse platea dictumst morbi vestibulum velit id', 0.08, '2023-01-25', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('lacus at turpis donec posuere metus vitae ipsum aliquam non', 10.59, '2023-07-24', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula', 0.16, '2023-08-23', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('morbi non quam nec dui luctus rutrum nulla tellus in', 3.94, '2023-11-10', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum', 13.83, '2023-01-23', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('phasellus in felis donec semper sapien a libero nam dui', 2.51, '2023-11-18', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('morbi ut odio cras mi pede malesuada in imperdiet et', 1.22, '2023-10-09', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('praesent blandit nam nulla integer pede justo lacinia eget tincidunt', 10.95, '2023-10-04', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('in blandit ultrices enim lorem ipsum dolor sit amet consectetuer', 5.03, '2023-03-10', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('sollicitudin ut suscipit a feugiat et eros vestibulum ac est', 6.27, '2023-10-03', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('pellentesque eget nunc donec quis orci eget orci vehicula condimentum', 6.04, '2023-05-28', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('at nulla suspendisse potenti cras in purus eu magna vulputate', 6.94, '2023-05-05', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('faucibus cursus urna ut tellus nulla ut erat id mauris', 12.83, '2023-05-05', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('turpis elementum ligula vehicula consequat morbi a ipsum integer a', 6.94, '2023-11-03', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('molestie sed justo pellentesque viverra pede ac diam cras pellentesque', 5.05, '2023-11-16', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('venenatis turpis enim blandit mi in porttitor pede justo eu', 12.69, '2023-05-24', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('morbi ut odio cras mi pede malesuada in imperdiet et', 11.4, '2023-01-01', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor', 5.45, '2023-05-08', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('faucibus accumsan odio curabitur convallis duis consequat dui nec nisi', 4.3, '2023-08-30', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('potenti cras in purus eu magna vulputate luctus cum sociis', 1.14, '2023-11-23', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('consequat lectus in est risus auctor sed tristique in tempus', 14.49, '2023-09-11', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('lectus suspendisse potenti in eleifend quam a odio in hac', 3.36, '2023-10-29', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('feugiat non pretium quis lectus suspendisse potenti in eleifend quam', 4.17, '2023-05-15', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis', 2.26, '2023-08-21', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('nec condimentum neque sapien placerat ante nulla justo aliquam quis', 6.4, '2023-02-11', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('porta volutpat erat quisque erat eros viverra eget congue eget', 8.3, '2023-07-28', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('cubilia curae nulla dapibus dolor vel est donec odio justo', 6.17, '2023-07-29', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('elementum ligula vehicula consequat morbi a ipsum integer a nibh', 0.96, '2023-12-12', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('pede posuere nonummy integer non velit donec diam neque vestibulum', 7.71, '2023-05-09', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('vitae mattis nibh ligula nec sem duis aliquam convallis nunc', 4.73, '2023-02-17', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('vestibulum sit amet cursus id turpis integer aliquet massa id', 14.14, '2023-09-25', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('pretium iaculis diam erat fermentum justo nec condimentum neque sapien', 3.29, '2023-09-15', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('posuere cubilia curae nulla dapibus dolor vel est donec odio', 12.2, '2023-05-16', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer', 10.48, '2023-04-14', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('sollicitudin ut suscipit a feugiat et eros vestibulum ac est', 6.88, '2023-01-11', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum', 10.48, '2023-05-05', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('elementum in hac habitasse platea dictumst morbi vestibulum velit id', 13.22, '2023-03-06', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae', 4.53, '2023-08-26', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('interdum mauris non ligula pellentesque ultrices phasellus id sapien in', 14.91, '2023-03-01', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper', 1.6, '2023-10-12', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('gravida nisi at nibh in hac habitasse platea dictumst aliquam', 9.26, '2023-08-05', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('tortor sollicitudin mi sit amet lobortis sapien sapien non mi', 10.02, '2023-07-05', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl', 11.17, '2023-03-26', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('mattis odio donec vitae nisi nam ultrices libero non mattis', 4.26, '2023-01-28', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('semper rutrum nulla nunc purus phasellus in felis donec semper', 11.45, '2023-09-25', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor', 8.78, '2023-02-19', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('quam nec dui luctus rutrum nulla tellus in sagittis dui', 3.76, '2023-08-22', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('vulputate elementum nullam varius nulla facilisi cras non velit nec', 13.4, '2023-03-19', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus', 13.46, '2023-07-12', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis', 13.9, '2023-05-24', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('libero rutrum ac lobortis vel dapibus at diam nam tristique', 1.66, '2023-02-17', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('lorem quisque ut erat curabitur gravida nisi at nibh in', 10.98, '2023-08-09', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('id consequat in consequat ut nulla sed accumsan felis ut', 6.14, '2023-10-08', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at', 3.73, '2023-02-11', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('dapibus augue vel accumsan tellus nisi eu orci mauris lacinia', 9.26, '2023-07-20', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('tristique est et tempus semper est quam pharetra magna ac', 13.54, '2023-10-03', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('ut mauris eget massa tempor convallis nulla neque libero convallis', 1.93, '2023-04-11', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem', 11.85, '2023-03-17', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('metus sapien ut nunc vestibulum ante ipsum primis in faucibus', 4.69, '2023-01-12', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla', 5.91, '2023-10-08', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit', 5.67, '2023-03-15', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('orci luctus et ultrices posuere cubilia curae duis faucibus accumsan', 5.77, '2023-07-16', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('quis libero nullam sit amet turpis elementum ligula vehicula consequat', 0.96, '2023-11-01', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('adipiscing elit proin risus praesent lectus vestibulum quam sapien varius', 7.37, '2023-07-15', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('fermentum justo nec condimentum neque sapien placerat ante nulla justo', 6.43, '2023-06-03', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('arcu sed augue aliquam erat volutpat in congue etiam justo', 2.25, '2023-10-01', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('convallis nulla neque libero convallis eget eleifend luctus ultricies eu', 9.22, '2023-10-27', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('lacinia aenean sit amet justo morbi ut odio cras mi', 8.77, '2023-09-18', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('orci luctus et ultrices posuere cubilia curae duis faucibus accumsan', 5.9, '2023-10-19', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('odio justo sollicitudin ut suscipit a feugiat et eros vestibulum', 7.6, '2023-01-21', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor', 14.16, '2023-08-02', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('ut mauris eget massa tempor convallis nulla neque libero convallis', 13.08, '2023-01-17', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('etiam justo etiam pretium iaculis justo in hac habitasse platea', 11.17, '2023-07-23', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien', 11.39, '2023-11-03', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('sem sed sagittis nam congue risus semper porta volutpat quam', 0.25, '2023-09-12', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet', 6.05, '2023-10-26', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('accumsan felis ut at dolor quis odio consequat varius integer', 10.64, '2023-08-01', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('consequat in consequat ut nulla sed accumsan felis ut at', 6.04, '2023-07-16', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('pretium nisl ut volutpat sapien arcu sed augue aliquam erat', 6.09, '2023-03-04', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('et commodo vulputate justo in blandit ultrices enim lorem ipsum', 11.08, '2023-09-24', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('lectus in quam fringilla rhoncus mauris enim leo rhoncus sed', 14.1, '2023-11-12', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('ac tellus semper interdum mauris ullamcorper purus sit amet nulla', 14.06, '2023-04-28', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('curae duis faucibus accumsan odio curabitur convallis duis consequat dui', 7.37, '2023-06-27', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('nullam orci pede venenatis non sodales sed tincidunt eu felis', 2.87, '2023-10-24', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('turpis adipiscing lorem vitae mattis nibh ligula nec sem duis', 14.07, '2023-01-11', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('non mauris morbi non lectus aliquam sit amet diam in', 11.47, '2023-05-14', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('suscipit nulla elit ac nulla sed vel enim sit amet', 3.87, '2023-01-31', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('orci mauris lacinia sapien quis libero nullam sit amet turpis', 6.07, '2023-12-22', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('ut nunc vestibulum ante ipsum primis in faucibus orci luctus', 12.53, '2023-01-03', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('ac est lacinia nisi venenatis tristique fusce congue diam id', 3.32, '2023-07-04', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('turpis donec posuere metus vitae ipsum aliquam non mauris morbi', 11.33, '2023-12-16', 1, 1);
INSERT INTO reciclable (descripcion, kilogramos, creado, usuario_id, ecopunto_id) VALUES ('ultrices mattis odio donec vitae nisi nam ultrices libero non', 0.66, '2023-10-07', 1, 1);

-- Poblamos al usuario con puntos
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-07-20', 5.56, 'convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis', 1, 1);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-11-28', 0.42, 'eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus', 1, 2);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-01-01', 8.24, 'convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci', 1, 3);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-09-24', 2.6, 'ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt', 1, 4);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-04-07', 6.08, 'sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et', 1, 5);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-05-08', 3.01, 'nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin', 1, 6);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-06-23', 0.8, 'lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta', 1, 7);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-02-19', 12.93, 'urna ut tellus nulla ut erat id mauris vulputate elementum', 1, 8);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-05-22', 0.22, 'donec ut dolor morbi vel lectus in quam fringilla rhoncus', 1, 9);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-01-10', 6.15, 'duis aliquam convallis nunc proin at turpis a pede posuere', 1, 10);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-08-02', 3.25, 'at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque', 1, 11);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-12-12', 7.06, 'Obtuviste Puntos', 1, 12);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-01-17', 8.95, 'amet diam in magna bibendum imperdiet nullam orci pede venenatis non', 1, 13);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-01-19', 4.92, 'cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus', 1, 14);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-09-21', 3.0, 'sed accumsan felis ut at dolor quis odio consequat varius', 1, 15);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-05-25', 13.16, 'rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet', 1, 16);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-04-28', 7.88, 'quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam', 1, 17);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-07-06', 14.79, 'nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit', 1, 18);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-12-12', 3.41, 'Obtuviste Puntos', 1, 19);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-07-11', 8.54, 'velit donec diam neque vestibulum eget vulputate ut ultrices vel augue', 1, 20);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-04-10', 10.21, 'penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue', 1, 21);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-05-01', 12.99, 'vivamus in felis eu sapien cursus vestibulum proin eu mi nulla', 1, 22);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-03-31', 12.59, 'odio cras mi pede malesuada in imperdiet et commodo vulputate justo', 1, 23);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-12-06', 6.24, 'Obtuviste Puntos', 1, 24);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-07-07', 7.59, 'sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean', 1, 25);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-07-25', 10.2, 'phasellus id sapien in sapien iaculis congue vivamus metus arcu', 1, 26);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-01-29', 14.17, 'suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst', 1, 27);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-06-13', 12.64, 'lobortis sapien sapien non mi integer ac neque duis bibendum', 1, 28);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-08-01', 14.22, 'pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu', 1, 29);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-01-20', 9.81, 'convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam', 1, 30);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-06-17', 6.68, 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 1, 31);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-08-08', 8.53, 'habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum', 1, 32);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-03-14', 11.97, 'quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi', 1, 33);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-12-22', 14.74, 'Obtuviste Puntos', 1, 34);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-07-23', 0.55, 'non quam nec dui luctus rutrum nulla tellus in sagittis', 1, 35);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-01-04', 8.96, 'nonummy integer non velit donec diam neque vestibulum eget vulputate ut', 1, 36);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-10-08', 11.7, 'aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non', 1, 37);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-09-07', 9.96, 'donec dapibus duis at velit eu est congue elementum in', 1, 38);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-07-31', 10.01, 'etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida', 1, 39);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-12-28', 4.55, 'Obtuviste Puntos', 1, 40);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-11-04', 2.97, 'sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed', 1, 41);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-11-25', 1.8, 'lectus vestibulum quam sapien varius ut blandit non interdum in ante', 1, 42);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-09-05', 11.25, 'ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo', 1, 43);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-02-08', 7.7, 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel', 1, 44);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-06-07', 7.79, 'massa id lobortis convallis tortor risus dapibus augue vel accumsan', 1, 45);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-05-01', 13.81, 'placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet', 1, 46);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-04-13', 7.03, 'ultrices libero non mattis pulvinar nulla pede ullamcorper augue a', 1, 47);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-10-28', 12.39, 'donec semper sapien a libero nam dui proin leo odio porttitor id', 1, 48);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-12-18', 13.2, 'Obtuviste Puntos', 1, 49);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-05-05', 6.48, 'non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl', 1, 50);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-03-01', 10.29, 'maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta', 1, 51);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-11-08', 1.27, 'libero nam dui proin leo odio porttitor id consequat in consequat', 1, 52);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-05-23', 3.81, 'libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse', 1, 53);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-01-14', 10.58, 'varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero', 1, 54);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-03-21', 10.07, 'blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel', 1, 55);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-01-18', 2.69, 'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus', 1, 56);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-09-09', 11.84, 'nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique', 1, 57);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-06-26', 8.21, 'orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis', 1, 58);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-12-13', 12.31, 'Obtuviste Puntos', 1, 59);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-05-10', 0.66, 'etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst', 1, 60);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-08-02', 3.96, 'luctus nec molestie sed justo pellentesque viverra pede ac diam', 1, 61);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-09-29', 7.42, 'et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare', 1, 62);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-02-09', 5.4, 'est risus auctor sed tristique in tempus sit amet sem fusce consequat', 1, 63);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-03-14', 2.5, 'sapien sapien non mi integer ac neque duis bibendum morbi non', 1, 64);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-07-10', 7.05, 'praesent id massa id nisl venenatis lacinia aenean sit amet justo', 1, 65);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-10-02', 10.9, 'feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac', 1, 66);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-01-28', 1.67, 'eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in', 1, 67);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-12-07', 6.46, 'Obtuviste Puntos', 1, 68);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-01-27', 0.81, 'luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum', 1, 69);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-10-01', 2.1, 'massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu', 1, 70);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-04-11', 14.69, 'elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante', 1, 71);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-01-18', 14.6, 'semper est quam pharetra magna ac consequat metus sapien ut nunc', 1, 72);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-11-19', 14.26, 'rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet', 1, 73);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-12-24', 1.68, 'Obtuviste Puntos', 1, 74);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-10-01', 6.53, 'aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue', 1, 75);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-07-07', 11.15, 'aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio', 1, 76);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-11-21', 14.33, 'nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit', 1, 77);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-12-05', 13.45, 'Obtuviste Puntos', 1, 78);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-10-20', 12.56, 'eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget', 1, 79);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-11-18', 3.6, 'sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas', 1, 80);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-01-07', 10.7, 'adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id', 1, 81);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-11-04', 9.95, 'rhoncus dui vel sem sed sagittis nam congue risus semper', 1, 82);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-07-14', 8.99, 'auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit', 1, 83);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-09-11', 2.92, 'sed ante vivamus tortor duis mattis egestas metus aenean fermentum', 1, 84);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-01-14', 11.64, 'nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem', 1, 85);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-08-08', 0.93, 'elit proin interdum mauris non ligula pellentesque ultrices phasellus id', 1, 86);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-11-07', 12.19, 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque', 1, 87);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-10-16', 7.02, 'cras in purus eu magna vulputate luctus cum sociis natoque penatibus', 1, 88);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-02-18', 2.12, 'sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at', 1, 89);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-10-20', 11.85, 'et tempus semper est quam pharetra magna ac consequat metus', 1, 90);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-09-25', 5.85, 'sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod', 1, 91);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-02-07', 12.94, 'justo morbi ut odio cras mi pede malesuada in imperdiet et commodo', 1, 92);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-12-20', 2.28, 'Obtuviste Puntos', 1, 93);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-06-05', 12.38, 'rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id', 1, 94);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-06-02', 7.8, 'ut suscipit a feugiat et eros vestibulum ac est lacinia nisi', 1, 95);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-07-16', 11.5, 'eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero', 1, 96);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-08-29', 3.15, 'accumsan odio curabitur convallis duis consequat dui nec nisi volutpat', 1, 97);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-07-08', 11.41, 'leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus', 1, 98);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-04-25', 13.66, 'vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio', 1, 99);
INSERT INTO punto (creado, cantidad, descripcion, usuario_id, reciclable_id) VALUES ('2023-09-30', 0.88, 'duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor', 1, 100);

INSERT INTO cupon (usuario_id, beneficio_id, creado) VALUES (1, 1, '2023-11-10');

INSERT INTO punto (creado, cantidad, descripcion, usuario_id, beneficio_id) values ('2023-12-23', -25, 'Intercambiaste Puntos', 1, 1);